// samples/MinimalApi.React/ClientApp/pages/Contacts/Create.tsx
import { useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import Layout from '../../Layout'

export default function Create() {
  const contact = useForm({ name: '', email: '' })
  const newsletter = useForm({ email: '' })

  const submitContact = (e: FormEvent) => {
    e.preventDefault()
    contact.post('/contacts')
  }
  const submitNewsletter = (e: FormEvent) => {
    e.preventDefault()
    newsletter.post('/newsletter', { errorBag: 'newsletter' })
  }

  return (
    <Layout>
      <h1>New contact</h1>
      <form onSubmit={submitContact}>
        <input data-testid="name" placeholder="Name" value={contact.data.name} onChange={(e) => contact.setData('name', e.target.value)} />
        <div data-testid="error-name">{contact.errors.name}</div>
        <input data-testid="email" placeholder="Email" value={contact.data.email} onChange={(e) => contact.setData('email', e.target.value)} />
        <div data-testid="error-email">{contact.errors.email}</div>
        <button data-testid="submit" type="submit" disabled={contact.processing}>Save</button>
      </form>
      <h2>Newsletter</h2>
      <form onSubmit={submitNewsletter}>
        <input data-testid="newsletter-email" placeholder="Email" value={newsletter.data.email} onChange={(e) => newsletter.setData('email', e.target.value)} />
        <div data-testid="error-newsletter-email">{newsletter.errors.email}</div>
        <button data-testid="newsletter-submit" type="submit" disabled={newsletter.processing}>Subscribe</button>
      </form>
    </Layout>
  )
}

// samples/FastEndpoints.Svelte/ClientApp/pages/Contacts/Create.svelte
<script lang="ts">
  import { useForm } from '@inertiajs/svelte'
  import Layout from '../../Layout.svelte'

  const contact = useForm({ name: '', email: '' })
  const newsletter = useForm({ email: '' })

  const submitContact = (e: SubmitEvent) => {
    e.preventDefault()
    contact.post('/contacts')
  }
  const submitNewsletter = (e: SubmitEvent) => {
    e.preventDefault()
    newsletter.post('/newsletter', { errorBag: 'newsletter' })
  }
</script>

<Layout>
  <h1>New contact</h1>
  <form onsubmit={submitContact}>
    <input data-testid="name" placeholder="Name" bind:value={contact.name} />
    <div data-testid="error-name">{contact.errors.name ?? ''}</div>
    <input data-testid="email" placeholder="Email" bind:value={contact.email} />
    <div data-testid="error-email">{contact.errors.email ?? ''}</div>
    <button data-testid="submit" type="submit" disabled={contact.processing}>Save</button>
  </form>
  <h2>Newsletter</h2>
  <form onsubmit={submitNewsletter}>
    <input data-testid="newsletter-email" placeholder="Email" bind:value={newsletter.email} />
    <div data-testid="error-newsletter-email">{newsletter.errors.email ?? ''}</div>
    <button data-testid="newsletter-submit" type="submit" disabled={newsletter.processing}>Subscribe</button>
  </form>
</Layout>
